version: "3.3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=josehz
      - POSTGRES_DB=postgres-basico

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jose.pineda@ae.edu.pe
      PGADMIN_DEFAULT_PASSWORD: mypassword
    ports:
      - "80:80"
    depends_on:
      - postgres